// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/models/shared"
	"net/http"
)

type CreateOrUpdateJourneyDatasourceRequest struct {
	JourneyID  string             `pathParam:"style=simple,explode=false,name=journeyId"`
	Datasource *shared.Datasource `request:"mediaType=application/json"`
}

func (c *CreateOrUpdateJourneyDatasourceRequest) GetJourneyID() string {
	if c == nil {
		return ""
	}
	return c.JourneyID
}

func (c *CreateOrUpdateJourneyDatasourceRequest) GetDatasource() *shared.Datasource {
	if c == nil {
		return nil
	}
	return c.Datasource
}

// CreateOrUpdateJourneyDatasource360NativeJourneysResponseBody - Internal Server Error
type CreateOrUpdateJourneyDatasource360NativeJourneysResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (c *CreateOrUpdateJourneyDatasource360NativeJourneysResponseBody) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

// #region class-body-createorupdatejourneydatasource360nativejourneysresponsebody
// #endregion class-body-createorupdatejourneydatasource360nativejourneysresponsebody

// CreateOrUpdateJourneyDatasourceResponseBody - Not found
type CreateOrUpdateJourneyDatasourceResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (c *CreateOrUpdateJourneyDatasourceResponseBody) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

type CreateOrUpdateJourneyDatasourceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The datasource has been created successfully
	Datasource *shared.Datasource
	// Not found
	FourHundredAndFourApplicationJSONObject *CreateOrUpdateJourneyDatasourceResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONObject *CreateOrUpdateJourneyDatasource360NativeJourneysResponseBody
}

func (c *CreateOrUpdateJourneyDatasourceResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateOrUpdateJourneyDatasourceResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateOrUpdateJourneyDatasourceResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateOrUpdateJourneyDatasourceResponse) GetDatasource() *shared.Datasource {
	if c == nil {
		return nil
	}
	return c.Datasource
}

func (c *CreateOrUpdateJourneyDatasourceResponse) GetFourHundredAndFourApplicationJSONObject() *CreateOrUpdateJourneyDatasourceResponseBody {
	if c == nil {
		return nil
	}
	return c.FourHundredAndFourApplicationJSONObject
}

func (c *CreateOrUpdateJourneyDatasourceResponse) GetFiveHundredApplicationJSONObject() *CreateOrUpdateJourneyDatasource360NativeJourneysResponseBody {
	if c == nil {
		return nil
	}
	return c.FiveHundredApplicationJSONObject
}
