// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteJourneyDatasourceByIDRequestBody struct {
	// ID of the datasource
	ID string `json:"id"`
}

func (d *DeleteJourneyDatasourceByIDRequestBody) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteJourneyDatasourceByIDRequest struct {
	JourneyID   string                                  `pathParam:"style=simple,explode=false,name=journeyId"`
	RequestBody *DeleteJourneyDatasourceByIDRequestBody `request:"mediaType=application/json"`
}

func (d *DeleteJourneyDatasourceByIDRequest) GetJourneyID() string {
	if d == nil {
		return ""
	}
	return d.JourneyID
}

func (d *DeleteJourneyDatasourceByIDRequest) GetRequestBody() *DeleteJourneyDatasourceByIDRequestBody {
	if d == nil {
		return nil
	}
	return d.RequestBody
}

// DeleteJourneyDatasourceByID360NativeJourneysResponseResponseBody - Internal Server Error
type DeleteJourneyDatasourceByID360NativeJourneysResponseResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (d *DeleteJourneyDatasourceByID360NativeJourneysResponseResponseBody) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

// #region class-body-deletejourneydatasourcebyid360nativejourneysresponseresponsebody
// #endregion class-body-deletejourneydatasourcebyid360nativejourneysresponseresponsebody

// DeleteJourneyDatasourceByID360NativeJourneysResponseBody - Not found
type DeleteJourneyDatasourceByID360NativeJourneysResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (d *DeleteJourneyDatasourceByID360NativeJourneysResponseBody) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

// #region class-body-deletejourneydatasourcebyid360nativejourneysresponsebody
// #endregion class-body-deletejourneydatasourcebyid360nativejourneysresponsebody

// DeleteJourneyDatasourceByIDResponseBody - The datasource has been deleted successfully
type DeleteJourneyDatasourceByIDResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (d *DeleteJourneyDatasourceByIDResponseBody) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

type DeleteJourneyDatasourceByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The datasource has been deleted successfully
	TwoHundredApplicationJSONObject *DeleteJourneyDatasourceByIDResponseBody
	// Not found
	FourHundredAndFourApplicationJSONObject *DeleteJourneyDatasourceByID360NativeJourneysResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONObject *DeleteJourneyDatasourceByID360NativeJourneysResponseResponseBody
}

func (d *DeleteJourneyDatasourceByIDResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteJourneyDatasourceByIDResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteJourneyDatasourceByIDResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteJourneyDatasourceByIDResponse) GetTwoHundredApplicationJSONObject() *DeleteJourneyDatasourceByIDResponseBody {
	if d == nil {
		return nil
	}
	return d.TwoHundredApplicationJSONObject
}

func (d *DeleteJourneyDatasourceByIDResponse) GetFourHundredAndFourApplicationJSONObject() *DeleteJourneyDatasourceByID360NativeJourneysResponseBody {
	if d == nil {
		return nil
	}
	return d.FourHundredAndFourApplicationJSONObject
}

func (d *DeleteJourneyDatasourceByIDResponse) GetFiveHundredApplicationJSONObject() *DeleteJourneyDatasourceByID360NativeJourneysResponseResponseBody {
	if d == nil {
		return nil
	}
	return d.FiveHundredApplicationJSONObject
}
