// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/models/shared"
	"net/http"
)

type GetDatasourceSchemasRequest struct {
	JourneyID    string `pathParam:"style=simple,explode=false,name=journeyId"`
	DatasourceID string `pathParam:"style=simple,explode=false,name=datasourceId"`
}

func (g *GetDatasourceSchemasRequest) GetJourneyID() string {
	if g == nil {
		return ""
	}
	return g.JourneyID
}

func (g *GetDatasourceSchemasRequest) GetDatasourceID() string {
	if g == nil {
		return ""
	}
	return g.DatasourceID
}

// GetDatasourceSchemas360NativeJourneysResponse500ResponseBody - Internal Server Error
type GetDatasourceSchemas360NativeJourneysResponse500ResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (g *GetDatasourceSchemas360NativeJourneysResponse500ResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

// #region class-body-getdatasourceschemas360nativejourneysresponse500responsebody
// #endregion class-body-getdatasourceschemas360nativejourneysresponse500responsebody

// GetDatasourceSchemas360NativeJourneysResponseResponseBody - Not found
type GetDatasourceSchemas360NativeJourneysResponseResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (g *GetDatasourceSchemas360NativeJourneysResponseResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

// #region class-body-getdatasourceschemas360nativejourneysresponseresponsebody
// #endregion class-body-getdatasourceschemas360nativejourneysresponseresponsebody

// GetDatasourceSchemas360NativeJourneysResponseBody - Forbidden
type GetDatasourceSchemas360NativeJourneysResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (g *GetDatasourceSchemas360NativeJourneysResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

// #region class-body-getdatasourceschemas360nativejourneysresponsebody
// #endregion class-body-getdatasourceschemas360nativejourneysresponsebody

// GetDatasourceSchemasResponseBody - Bad Request
type GetDatasourceSchemasResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (g *GetDatasourceSchemasResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

type GetDatasourceSchemasResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The schemas have been retrieved successfully
	DatasourceSchema *shared.DatasourceSchema
	// Bad Request
	FourHundredApplicationJSONObject *GetDatasourceSchemasResponseBody
	// Forbidden
	FourHundredAndThreeApplicationJSONObject *GetDatasourceSchemas360NativeJourneysResponseBody
	// Not found
	FourHundredAndFourApplicationJSONObject *GetDatasourceSchemas360NativeJourneysResponseResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONObject *GetDatasourceSchemas360NativeJourneysResponse500ResponseBody
}

func (g *GetDatasourceSchemasResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetDatasourceSchemasResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetDatasourceSchemasResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetDatasourceSchemasResponse) GetDatasourceSchema() *shared.DatasourceSchema {
	if g == nil {
		return nil
	}
	return g.DatasourceSchema
}

func (g *GetDatasourceSchemasResponse) GetFourHundredApplicationJSONObject() *GetDatasourceSchemasResponseBody {
	if g == nil {
		return nil
	}
	return g.FourHundredApplicationJSONObject
}

func (g *GetDatasourceSchemasResponse) GetFourHundredAndThreeApplicationJSONObject() *GetDatasourceSchemas360NativeJourneysResponseBody {
	if g == nil {
		return nil
	}
	return g.FourHundredAndThreeApplicationJSONObject
}

func (g *GetDatasourceSchemasResponse) GetFourHundredAndFourApplicationJSONObject() *GetDatasourceSchemas360NativeJourneysResponseResponseBody {
	if g == nil {
		return nil
	}
	return g.FourHundredAndFourApplicationJSONObject
}

func (g *GetDatasourceSchemasResponse) GetFiveHundredApplicationJSONObject() *GetDatasourceSchemas360NativeJourneysResponse500ResponseBody {
	if g == nil {
		return nil
	}
	return g.FiveHundredApplicationJSONObject
}
