// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/models/shared"
	"net/http"
)

type GetJourneyDatasourcesRequest struct {
	JourneyID string `pathParam:"style=simple,explode=false,name=journeyId"`
}

func (g *GetJourneyDatasourcesRequest) GetJourneyID() string {
	if g == nil {
		return ""
	}
	return g.JourneyID
}

// GetJourneyDatasources360NativeJourneysResponseBody - Internal Server Error
type GetJourneyDatasources360NativeJourneysResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (g *GetJourneyDatasources360NativeJourneysResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

// #region class-body-getjourneydatasources360nativejourneysresponsebody
// #endregion class-body-getjourneydatasources360nativejourneysresponsebody

// GetJourneyDatasourcesResponseBody - Not found
type GetJourneyDatasourcesResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (g *GetJourneyDatasourcesResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

type GetJourneyDatasourcesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The datasources have been retrieved successfully
	TwoHundredApplicationJSONDatasources []shared.Datasource
	// Not found
	FourHundredAndFourApplicationJSONObject *GetJourneyDatasourcesResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONObject *GetJourneyDatasources360NativeJourneysResponseBody
}

func (g *GetJourneyDatasourcesResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetJourneyDatasourcesResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetJourneyDatasourcesResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetJourneyDatasourcesResponse) GetTwoHundredApplicationJSONDatasources() []shared.Datasource {
	if g == nil {
		return nil
	}
	return g.TwoHundredApplicationJSONDatasources
}

func (g *GetJourneyDatasourcesResponse) GetFourHundredAndFourApplicationJSONObject() *GetJourneyDatasourcesResponseBody {
	if g == nil {
		return nil
	}
	return g.FourHundredAndFourApplicationJSONObject
}

func (g *GetJourneyDatasourcesResponse) GetFiveHundredApplicationJSONObject() *GetJourneyDatasources360NativeJourneysResponseBody {
	if g == nil {
		return nil
	}
	return g.FiveHundredApplicationJSONObject
}
