// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/models/shared"
	"net/http"
)

type GetJourneyDatasourceByIDRequest struct {
	JourneyID    string `pathParam:"style=simple,explode=false,name=journeyId"`
	DatasourceID string `pathParam:"style=simple,explode=false,name=datasourceId"`
}

func (g *GetJourneyDatasourceByIDRequest) GetJourneyID() string {
	if g == nil {
		return ""
	}
	return g.JourneyID
}

func (g *GetJourneyDatasourceByIDRequest) GetDatasourceID() string {
	if g == nil {
		return ""
	}
	return g.DatasourceID
}

// GetJourneyDatasourceByID360NativeJourneysResponseBody - Internal Server Error
type GetJourneyDatasourceByID360NativeJourneysResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (g *GetJourneyDatasourceByID360NativeJourneysResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

// #region class-body-getjourneydatasourcebyid360nativejourneysresponsebody
// #endregion class-body-getjourneydatasourcebyid360nativejourneysresponsebody

// GetJourneyDatasourceByIDResponseBody - Not found
type GetJourneyDatasourceByIDResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (g *GetJourneyDatasourceByIDResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

type GetJourneyDatasourceByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The datasource has been retrieved successfully
	Datasource *shared.Datasource
	// Not found
	FourHundredAndFourApplicationJSONObject *GetJourneyDatasourceByIDResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONObject *GetJourneyDatasourceByID360NativeJourneysResponseBody
}

func (g *GetJourneyDatasourceByIDResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetJourneyDatasourceByIDResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetJourneyDatasourceByIDResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetJourneyDatasourceByIDResponse) GetDatasource() *shared.Datasource {
	if g == nil {
		return nil
	}
	return g.Datasource
}

func (g *GetJourneyDatasourceByIDResponse) GetFourHundredAndFourApplicationJSONObject() *GetJourneyDatasourceByIDResponseBody {
	if g == nil {
		return nil
	}
	return g.FourHundredAndFourApplicationJSONObject
}

func (g *GetJourneyDatasourceByIDResponse) GetFiveHundredApplicationJSONObject() *GetJourneyDatasourceByID360NativeJourneysResponseBody {
	if g == nil {
		return nil
	}
	return g.FiveHundredApplicationJSONObject
}
