// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/models/shared"
	"net/http"
)

type GetJourneyDatasourceByCompositeIDRequest struct {
	CompositeID string `pathParam:"style=simple,explode=false,name=compositeId"`
}

func (g *GetJourneyDatasourceByCompositeIDRequest) GetCompositeID() string {
	if g == nil {
		return ""
	}
	return g.CompositeID
}

// GetJourneyDatasourceByCompositeID360NativeJourneysResponseBody - Internal Server Error
type GetJourneyDatasourceByCompositeID360NativeJourneysResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (g *GetJourneyDatasourceByCompositeID360NativeJourneysResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

// #region class-body-getjourneydatasourcebycompositeid360nativejourneysresponsebody
// #endregion class-body-getjourneydatasourcebycompositeid360nativejourneysresponsebody

// GetJourneyDatasourceByCompositeIDResponseBody - Not found
type GetJourneyDatasourceByCompositeIDResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (g *GetJourneyDatasourceByCompositeIDResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

type GetJourneyDatasourceByCompositeIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The datasource has been retrieved successfully
	Datasource *shared.Datasource
	// Not found
	FourHundredAndFourApplicationJSONObject *GetJourneyDatasourceByCompositeIDResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONObject *GetJourneyDatasourceByCompositeID360NativeJourneysResponseBody
}

func (g *GetJourneyDatasourceByCompositeIDResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetJourneyDatasourceByCompositeIDResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetJourneyDatasourceByCompositeIDResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetJourneyDatasourceByCompositeIDResponse) GetDatasource() *shared.Datasource {
	if g == nil {
		return nil
	}
	return g.Datasource
}

func (g *GetJourneyDatasourceByCompositeIDResponse) GetFourHundredAndFourApplicationJSONObject() *GetJourneyDatasourceByCompositeIDResponseBody {
	if g == nil {
		return nil
	}
	return g.FourHundredAndFourApplicationJSONObject
}

func (g *GetJourneyDatasourceByCompositeIDResponse) GetFiveHundredApplicationJSONObject() *GetJourneyDatasourceByCompositeID360NativeJourneysResponseBody {
	if g == nil {
		return nil
	}
	return g.FiveHundredApplicationJSONObject
}
