// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/models/shared"
	"net/http"
)

// SearchJourneyEntities360NativeJourneysResponseResponseBody - Internal Server Error
type SearchJourneyEntities360NativeJourneysResponseResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (s *SearchJourneyEntities360NativeJourneysResponseResponseBody) GetMessage() *string {
	if s == nil {
		return nil
	}
	return s.Message
}

// #region class-body-searchjourneyentities360nativejourneysresponseresponsebody
// #endregion class-body-searchjourneyentities360nativejourneysresponseresponsebody

// SearchJourneyEntities360NativeJourneysResponseBody - Not found
type SearchJourneyEntities360NativeJourneysResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (s *SearchJourneyEntities360NativeJourneysResponseBody) GetMessage() *string {
	if s == nil {
		return nil
	}
	return s.Message
}

// #region class-body-searchjourneyentities360nativejourneysresponsebody
// #endregion class-body-searchjourneyentities360nativejourneysresponsebody

type SearchJourneyEntitiesResponseBodyType string

const (
	SearchJourneyEntitiesResponseBodyTypeEntityResponseWithHits        SearchJourneyEntitiesResponseBodyType = "EntityResponseWithHits"
	SearchJourneyEntitiesResponseBodyTypeEntityResponseGroupedWithHits SearchJourneyEntitiesResponseBodyType = "EntityResponseGroupedWithHits"
)

// SearchJourneyEntitiesResponseBody - The entities have been retrieved successfully for the portal user.
type SearchJourneyEntitiesResponseBody struct {
	EntityResponseWithHits        *shared.EntityResponseWithHits        `queryParam:"inline" union:"member"`
	EntityResponseGroupedWithHits *shared.EntityResponseGroupedWithHits `queryParam:"inline" union:"member"`

	Type SearchJourneyEntitiesResponseBodyType
}

func CreateSearchJourneyEntitiesResponseBodyEntityResponseWithHits(entityResponseWithHits shared.EntityResponseWithHits) SearchJourneyEntitiesResponseBody {
	typ := SearchJourneyEntitiesResponseBodyTypeEntityResponseWithHits

	return SearchJourneyEntitiesResponseBody{
		EntityResponseWithHits: &entityResponseWithHits,
		Type:                   typ,
	}
}

func CreateSearchJourneyEntitiesResponseBodyEntityResponseGroupedWithHits(entityResponseGroupedWithHits shared.EntityResponseGroupedWithHits) SearchJourneyEntitiesResponseBody {
	typ := SearchJourneyEntitiesResponseBodyTypeEntityResponseGroupedWithHits

	return SearchJourneyEntitiesResponseBody{
		EntityResponseGroupedWithHits: &entityResponseGroupedWithHits,
		Type:                          typ,
	}
}

func (u *SearchJourneyEntitiesResponseBody) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var entityResponseWithHits shared.EntityResponseWithHits = shared.EntityResponseWithHits{}
	if err := utils.UnmarshalJSON(data, &entityResponseWithHits, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SearchJourneyEntitiesResponseBodyTypeEntityResponseWithHits,
			Value: &entityResponseWithHits,
		})
	}

	var entityResponseGroupedWithHits shared.EntityResponseGroupedWithHits = shared.EntityResponseGroupedWithHits{}
	if err := utils.UnmarshalJSON(data, &entityResponseGroupedWithHits, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SearchJourneyEntitiesResponseBodyTypeEntityResponseGroupedWithHits,
			Value: &entityResponseGroupedWithHits,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for SearchJourneyEntitiesResponseBody", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for SearchJourneyEntitiesResponseBody", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(SearchJourneyEntitiesResponseBodyType)
	switch best.Type {
	case SearchJourneyEntitiesResponseBodyTypeEntityResponseWithHits:
		u.EntityResponseWithHits = best.Value.(*shared.EntityResponseWithHits)
		return nil
	case SearchJourneyEntitiesResponseBodyTypeEntityResponseGroupedWithHits:
		u.EntityResponseGroupedWithHits = best.Value.(*shared.EntityResponseGroupedWithHits)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for SearchJourneyEntitiesResponseBody", string(data))
}

func (u SearchJourneyEntitiesResponseBody) MarshalJSON() ([]byte, error) {
	if u.EntityResponseWithHits != nil {
		return utils.MarshalJSON(u.EntityResponseWithHits, "", true)
	}

	if u.EntityResponseGroupedWithHits != nil {
		return utils.MarshalJSON(u.EntityResponseGroupedWithHits, "", true)
	}

	return nil, errors.New("could not marshal union type SearchJourneyEntitiesResponseBody: all fields are null")
}

type SearchJourneyEntitiesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The entities have been retrieved successfully for the portal user.
	TwoHundredApplicationJSONOneOf *SearchJourneyEntitiesResponseBody
	// Not found
	FourHundredAndFourApplicationJSONObject *SearchJourneyEntities360NativeJourneysResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONObject *SearchJourneyEntities360NativeJourneysResponseResponseBody
}

func (s *SearchJourneyEntitiesResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SearchJourneyEntitiesResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SearchJourneyEntitiesResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *SearchJourneyEntitiesResponse) GetTwoHundredApplicationJSONOneOf() *SearchJourneyEntitiesResponseBody {
	if s == nil {
		return nil
	}
	return s.TwoHundredApplicationJSONOneOf
}

func (s *SearchJourneyEntitiesResponse) GetFourHundredAndFourApplicationJSONObject() *SearchJourneyEntities360NativeJourneysResponseBody {
	if s == nil {
		return nil
	}
	return s.FourHundredAndFourApplicationJSONObject
}

func (s *SearchJourneyEntitiesResponse) GetFiveHundredApplicationJSONObject() *SearchJourneyEntities360NativeJourneysResponseResponseBody {
	if s == nil {
		return nil
	}
	return s.FiveHundredApplicationJSONObject
}
