// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/models/shared"
	"net/http"
)

// UpsertJourneyDatasource360NativeJourneysResponseBody - Internal Server Error
type UpsertJourneyDatasource360NativeJourneysResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (u *UpsertJourneyDatasource360NativeJourneysResponseBody) GetMessage() *string {
	if u == nil {
		return nil
	}
	return u.Message
}

// #region class-body-upsertjourneydatasource360nativejourneysresponsebody
// #endregion class-body-upsertjourneydatasource360nativejourneysresponsebody

// UpsertJourneyDatasourceResponseBody - Not found
type UpsertJourneyDatasourceResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (u *UpsertJourneyDatasourceResponseBody) GetMessage() *string {
	if u == nil {
		return nil
	}
	return u.Message
}

type UpsertJourneyDatasourceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The datasource has been created or updated successfully
	Datasource *shared.Datasource
	// Not found
	FourHundredAndFourApplicationJSONObject *UpsertJourneyDatasourceResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONObject *UpsertJourneyDatasource360NativeJourneysResponseBody
}

func (u *UpsertJourneyDatasourceResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpsertJourneyDatasourceResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpsertJourneyDatasourceResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpsertJourneyDatasourceResponse) GetDatasource() *shared.Datasource {
	if u == nil {
		return nil
	}
	return u.Datasource
}

func (u *UpsertJourneyDatasourceResponse) GetFourHundredAndFourApplicationJSONObject() *UpsertJourneyDatasourceResponseBody {
	if u == nil {
		return nil
	}
	return u.FourHundredAndFourApplicationJSONObject
}

func (u *UpsertJourneyDatasourceResponse) GetFiveHundredApplicationJSONObject() *UpsertJourneyDatasource360NativeJourneysResponseBody {
	if u == nil {
		return nil
	}
	return u.FiveHundredApplicationJSONObject
}
