// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/internal/utils"
)

type BlockValueType string

const (
	BlockValueTypeBlock BlockValueType = "block"
)

func (e BlockValueType) ToPointer() *BlockValueType {
	return &e
}
func (e *BlockValueType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "block":
		*e = BlockValueType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BlockValueType: %v", v)
	}
}

type BlockValue struct {
	Type *BlockValueType `json:"type,omitempty"`
	// Block ID
	BlockID *string `json:"blockId,omitempty"`
	// Path to the block
	Path *string `json:"path,omitempty"`
	// Preview with value
	PreviewWith *string `json:"previewWith,omitempty"`
}

func (b BlockValue) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BlockValue) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BlockValue) GetType() *BlockValueType {
	if b == nil {
		return nil
	}
	return b.Type
}

func (b *BlockValue) GetBlockID() *string {
	if b == nil {
		return nil
	}
	return b.BlockID
}

func (b *BlockValue) GetPath() *string {
	if b == nil {
		return nil
	}
	return b.Path
}

func (b *BlockValue) GetPreviewWith() *string {
	if b == nil {
		return nil
	}
	return b.PreviewWith
}
