// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/internal/utils"
)

type ComparisonValueType string

const (
	ComparisonValueTypeConstantValue ComparisonValueType = "ConstantValue"
	ComparisonValueTypeBlockValue    ComparisonValueType = "BlockValue"
	ComparisonValueTypeVariableValue ComparisonValueType = "VariableValue"
	ComparisonValueTypeContextValue  ComparisonValueType = "ContextValue"
)

type ComparisonValue struct {
	ConstantValue *ConstantValue `queryParam:"inline" union:"member"`
	BlockValue    *BlockValue    `queryParam:"inline" union:"member"`
	VariableValue *VariableValue `queryParam:"inline" union:"member"`
	ContextValue  *ContextValue  `queryParam:"inline" union:"member"`

	Type ComparisonValueType
}

func CreateComparisonValueConstantValue(constantValue ConstantValue) ComparisonValue {
	typ := ComparisonValueTypeConstantValue

	return ComparisonValue{
		ConstantValue: &constantValue,
		Type:          typ,
	}
}

func CreateComparisonValueBlockValue(blockValue BlockValue) ComparisonValue {
	typ := ComparisonValueTypeBlockValue

	return ComparisonValue{
		BlockValue: &blockValue,
		Type:       typ,
	}
}

func CreateComparisonValueVariableValue(variableValue VariableValue) ComparisonValue {
	typ := ComparisonValueTypeVariableValue

	return ComparisonValue{
		VariableValue: &variableValue,
		Type:          typ,
	}
}

func CreateComparisonValueContextValue(contextValue ContextValue) ComparisonValue {
	typ := ComparisonValueTypeContextValue

	return ComparisonValue{
		ContextValue: &contextValue,
		Type:         typ,
	}
}

func (u *ComparisonValue) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var constantValue ConstantValue = ConstantValue{}
	if err := utils.UnmarshalJSON(data, &constantValue, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ComparisonValueTypeConstantValue,
			Value: &constantValue,
		})
	}

	var blockValue BlockValue = BlockValue{}
	if err := utils.UnmarshalJSON(data, &blockValue, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ComparisonValueTypeBlockValue,
			Value: &blockValue,
		})
	}

	var variableValue VariableValue = VariableValue{}
	if err := utils.UnmarshalJSON(data, &variableValue, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ComparisonValueTypeVariableValue,
			Value: &variableValue,
		})
	}

	var contextValue ContextValue = ContextValue{}
	if err := utils.UnmarshalJSON(data, &contextValue, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ComparisonValueTypeContextValue,
			Value: &contextValue,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ComparisonValue", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ComparisonValue", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ComparisonValueType)
	switch best.Type {
	case ComparisonValueTypeConstantValue:
		u.ConstantValue = best.Value.(*ConstantValue)
		return nil
	case ComparisonValueTypeBlockValue:
		u.BlockValue = best.Value.(*BlockValue)
		return nil
	case ComparisonValueTypeVariableValue:
		u.VariableValue = best.Value.(*VariableValue)
		return nil
	case ComparisonValueTypeContextValue:
		u.ContextValue = best.Value.(*ContextValue)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ComparisonValue", string(data))
}

func (u ComparisonValue) MarshalJSON() ([]byte, error) {
	if u.ConstantValue != nil {
		return utils.MarshalJSON(u.ConstantValue, "", true)
	}

	if u.BlockValue != nil {
		return utils.MarshalJSON(u.BlockValue, "", true)
	}

	if u.VariableValue != nil {
		return utils.MarshalJSON(u.VariableValue, "", true)
	}

	if u.ContextValue != nil {
		return utils.MarshalJSON(u.ContextValue, "", true)
	}

	return nil, errors.New("could not marshal union type ComparisonValue: all fields are null")
}

type ClassicDatasourceFilter struct {
	// ID of the filter
	ID *string `json:"id,omitempty"`
	// Field name to filter on
	Field string `json:"field"`
	// Filter operator
	Operator        FilterOperator  `json:"operator"`
	ComparisonValue ComparisonValue `json:"comparisonValue"`
}

func (c ClassicDatasourceFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClassicDatasourceFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClassicDatasourceFilter) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *ClassicDatasourceFilter) GetField() string {
	if c == nil {
		return ""
	}
	return c.Field
}

func (c *ClassicDatasourceFilter) GetOperator() FilterOperator {
	if c == nil {
		return FilterOperator("")
	}
	return c.Operator
}

func (c *ClassicDatasourceFilter) GetComparisonValue() ComparisonValue {
	if c == nil {
		return ComparisonValue{}
	}
	return c.ComparisonValue
}
