// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/internal/utils"
)

type Type string

const (
	TypeConstant Type = "constant"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "constant":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type ConstantValue struct {
	Type Type `json:"type"`
	// Constant value
	Value string `json:"value"`
	// Preview with value
	PreviewWith *string `json:"previewWith,omitempty"`
}

func (c ConstantValue) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConstantValue) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConstantValue) GetType() Type {
	if c == nil {
		return Type("")
	}
	return c.Type
}

func (c *ConstantValue) GetValue() string {
	if c == nil {
		return ""
	}
	return c.Value
}

func (c *ConstantValue) GetPreviewWith() *string {
	if c == nil {
		return nil
	}
	return c.PreviewWith
}
