// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/internal/utils"
)

type ContextValueType string

const (
	ContextValueTypeContext ContextValueType = "context"
)

func (e ContextValueType) ToPointer() *ContextValueType {
	return &e
}
func (e *ContextValueType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "context":
		*e = ContextValueType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContextValueType: %v", v)
	}
}

type ContextValue struct {
	Type *ContextValueType `json:"type,omitempty"`
	// Context parameter ID
	ContextParameterID *string `json:"contextParameterId,omitempty"`
	// Preview with value
	PreviewWith *string `json:"previewWith,omitempty"`
}

func (c ContextValue) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContextValue) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContextValue) GetType() *ContextValueType {
	if c == nil {
		return nil
	}
	return c.Type
}

func (c *ContextValue) GetContextParameterID() *string {
	if c == nil {
		return nil
	}
	return c.ContextParameterID
}

func (c *ContextValue) GetPreviewWith() *string {
	if c == nil {
		return nil
	}
	return c.PreviewWith
}
