// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// DatasourceUpsertRequest - Request body for upserting a datasource when both journeyId and id are known upfront (blueprint flows).
type DatasourceUpsertRequest struct {
	// Name of the datasource
	Name string `json:"name"`
	// ID of the datasource
	ID string `json:"id"`
	// Journey ID
	JourneyID string `json:"journeyId"`
	// Composite identifier in the form `journeyId:datasourceId`. Returned by GET responses and accepted by endpoints that look up a datasource by composite id.
	CompositeID *string `json:"compositeId,omitempty"`
	// Source identifier for the search
	Source string `json:"source"`
	// List of entity fields to include in search results
	Fields  []string             `json:"fields"`
	Filters [][]DatasourceFilter `json:"filters,omitempty"`
	Search  *SearchParams        `json:"search,omitempty"`
	Group   *GroupParams         `json:"group,omitempty"`
}

func (d *DatasourceUpsertRequest) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DatasourceUpsertRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DatasourceUpsertRequest) GetJourneyID() string {
	if d == nil {
		return ""
	}
	return d.JourneyID
}

func (d *DatasourceUpsertRequest) GetCompositeID() *string {
	if d == nil {
		return nil
	}
	return d.CompositeID
}

func (d *DatasourceUpsertRequest) GetSource() string {
	if d == nil {
		return ""
	}
	return d.Source
}

func (d *DatasourceUpsertRequest) GetFields() []string {
	if d == nil {
		return []string{}
	}
	return d.Fields
}

func (d *DatasourceUpsertRequest) GetFilters() [][]DatasourceFilter {
	if d == nil {
		return nil
	}
	return d.Filters
}

func (d *DatasourceUpsertRequest) GetSearch() *SearchParams {
	if d == nil {
		return nil
	}
	return d.Search
}

func (d *DatasourceUpsertRequest) GetGroup() *GroupParams {
	if d == nil {
		return nil
	}
	return d.Group
}
