// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Datasource struct {
	// Name of the datasource
	Name string `json:"name"`
	// ID of the datasource
	ID *string `json:"id,omitempty"`
	// Journey ID
	JourneyID *string `json:"journeyId,omitempty"`
	// Composite identifier in the form `journeyId:datasourceId`. Returned by GET responses and accepted by endpoints that look up a datasource by composite id.
	CompositeID *string `json:"compositeId,omitempty"`
	// Source identifier for the search
	Source string `json:"source"`
	// List of entity fields to include in search results
	Fields  []string             `json:"fields"`
	Filters [][]DatasourceFilter `json:"filters,omitempty"`
	Search  *SearchParams        `json:"search,omitempty"`
	Group   *GroupParams         `json:"group,omitempty"`
}

func (d *Datasource) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *Datasource) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *Datasource) GetJourneyID() *string {
	if d == nil {
		return nil
	}
	return d.JourneyID
}

func (d *Datasource) GetCompositeID() *string {
	if d == nil {
		return nil
	}
	return d.CompositeID
}

func (d *Datasource) GetSource() string {
	if d == nil {
		return ""
	}
	return d.Source
}

func (d *Datasource) GetFields() []string {
	if d == nil {
		return []string{}
	}
	return d.Fields
}

func (d *Datasource) GetFilters() [][]DatasourceFilter {
	if d == nil {
		return nil
	}
	return d.Filters
}

func (d *Datasource) GetSearch() *SearchParams {
	if d == nil {
		return nil
	}
	return d.Search
}

func (d *Datasource) GetGroup() *GroupParams {
	if d == nil {
		return nil
	}
	return d.Group
}
