// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/internal/utils"
)

type DatasourceFilterType string

const (
	DatasourceFilterTypeClassicDatasourceFilter DatasourceFilterType = "ClassicDatasourceFilter"
	DatasourceFilterTypeTargetDatasourceFilter  DatasourceFilterType = "TargetDatasourceFilter"
)

type DatasourceFilter struct {
	ClassicDatasourceFilter *ClassicDatasourceFilter `queryParam:"inline" union:"member"`
	TargetDatasourceFilter  *TargetDatasourceFilter  `queryParam:"inline" union:"member"`

	Type DatasourceFilterType
}

func CreateDatasourceFilterClassicDatasourceFilter(classicDatasourceFilter ClassicDatasourceFilter) DatasourceFilter {
	typ := DatasourceFilterTypeClassicDatasourceFilter

	return DatasourceFilter{
		ClassicDatasourceFilter: &classicDatasourceFilter,
		Type:                    typ,
	}
}

func CreateDatasourceFilterTargetDatasourceFilter(targetDatasourceFilter TargetDatasourceFilter) DatasourceFilter {
	typ := DatasourceFilterTypeTargetDatasourceFilter

	return DatasourceFilter{
		TargetDatasourceFilter: &targetDatasourceFilter,
		Type:                   typ,
	}
}

func (u *DatasourceFilter) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var classicDatasourceFilter ClassicDatasourceFilter = ClassicDatasourceFilter{}
	if err := utils.UnmarshalJSON(data, &classicDatasourceFilter, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  DatasourceFilterTypeClassicDatasourceFilter,
			Value: &classicDatasourceFilter,
		})
	}

	var targetDatasourceFilter TargetDatasourceFilter = TargetDatasourceFilter{}
	if err := utils.UnmarshalJSON(data, &targetDatasourceFilter, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  DatasourceFilterTypeTargetDatasourceFilter,
			Value: &targetDatasourceFilter,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for DatasourceFilter", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for DatasourceFilter", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(DatasourceFilterType)
	switch best.Type {
	case DatasourceFilterTypeClassicDatasourceFilter:
		u.ClassicDatasourceFilter = best.Value.(*ClassicDatasourceFilter)
		return nil
	case DatasourceFilterTypeTargetDatasourceFilter:
		u.TargetDatasourceFilter = best.Value.(*TargetDatasourceFilter)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for DatasourceFilter", string(data))
}

func (u DatasourceFilter) MarshalJSON() ([]byte, error) {
	if u.ClassicDatasourceFilter != nil {
		return utils.MarshalJSON(u.ClassicDatasourceFilter, "", true)
	}

	if u.TargetDatasourceFilter != nil {
		return utils.MarshalJSON(u.TargetDatasourceFilter, "", true)
	}

	return nil, errors.New("could not marshal union type DatasourceFilter: all fields are null")
}
