// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DatasourceSchema struct {
	Root SchemaDefinition `json:"root"`
	// Map of relation schema slugs to their schema definitions
	RelationSchemas map[string]SchemaDefinition `json:"relationSchemas"`
}

func (d *DatasourceSchema) GetRoot() SchemaDefinition {
	if d == nil {
		return SchemaDefinition{}
	}
	return d.Root
}

func (d *DatasourceSchema) GetRelationSchemas() map[string]SchemaDefinition {
	if d == nil {
		return map[string]SchemaDefinition{}
	}
	return d.RelationSchemas
}
