// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Pagination control for the search API
type Pagination struct {
	// Number of entities per page
	Size *float64 `json:"size,omitempty"`
	// Page number for pagination
	Page int64 `json:"page"`
}

func (p *Pagination) GetSize() *float64 {
	if p == nil {
		return nil
	}
	return p.Size
}

func (p *Pagination) GetPage() int64 {
	if p == nil {
		return 0
	}
	return p.Page
}

type EntitySearchParams struct {
	// Source identifier for the search
	Source string `json:"source"`
	// List of entity fields to include in search results
	Fields []string `json:"fields"`
	// An array of filter groups which will be resolved with OR operator.
	//
	// Example:
	//   [[filter1, filter2], [filter3]] => (filter1 AND filter2) OR (filter3)
	//
	Filters [][]Filters   `json:"filters,omitempty"`
	Search  *SearchParams `json:"search,omitempty"`
	Group   *GroupParams  `json:"group,omitempty"`
	// Pagination control for the search API
	Pagination Pagination `json:"pagination"`
}

func (e *EntitySearchParams) GetSource() string {
	if e == nil {
		return ""
	}
	return e.Source
}

func (e *EntitySearchParams) GetFields() []string {
	if e == nil {
		return []string{}
	}
	return e.Fields
}

func (e *EntitySearchParams) GetFilters() [][]Filters {
	if e == nil {
		return nil
	}
	return e.Filters
}

func (e *EntitySearchParams) GetSearch() *SearchParams {
	if e == nil {
		return nil
	}
	return e.Search
}

func (e *EntitySearchParams) GetGroup() *GroupParams {
	if e == nil {
		return nil
	}
	return e.Group
}

func (e *EntitySearchParams) GetPagination() Pagination {
	if e == nil {
		return Pagination{}
	}
	return e.Pagination
}
