// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/internal/utils"
)

// EntityResponseWithHitsPagination - Pagination metadata
type EntityResponseWithHitsPagination struct {
	// Starting offset for the current page
	From *float64 `json:"from,omitempty"`
	// Number of entities per page
	Size *float64 `json:"size,omitempty"`
	// Total number of entities available
	Total *float64 `json:"total,omitempty"`
	// Whether there are more entities available beyond the current page
	HasMore *bool `json:"has_more,omitempty"`
}

func (e EntityResponseWithHitsPagination) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityResponseWithHitsPagination) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntityResponseWithHitsPagination) GetFrom() *float64 {
	if e == nil {
		return nil
	}
	return e.From
}

func (e *EntityResponseWithHitsPagination) GetSize() *float64 {
	if e == nil {
		return nil
	}
	return e.Size
}

func (e *EntityResponseWithHitsPagination) GetTotal() *float64 {
	if e == nil {
		return nil
	}
	return e.Total
}

func (e *EntityResponseWithHitsPagination) GetHasMore() *bool {
	if e == nil {
		return nil
	}
	return e.HasMore
}

// EntityResponseWithHits - Response for entity search requests
type EntityResponseWithHits struct {
	Results []EntityItem `json:"results,omitempty"`
	// Pagination metadata
	Pagination *EntityResponseWithHitsPagination `json:"pagination,omitempty"`
	// Number of entities returned in this response
	Hits *float64 `json:"hits,omitempty"`
}

func (e EntityResponseWithHits) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityResponseWithHits) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntityResponseWithHits) GetResults() []EntityItem {
	if e == nil {
		return nil
	}
	return e.Results
}

func (e *EntityResponseWithHits) GetPagination() *EntityResponseWithHitsPagination {
	if e == nil {
		return nil
	}
	return e.Pagination
}

func (e *EntityResponseWithHits) GetHits() *float64 {
	if e == nil {
		return nil
	}
	return e.Hits
}
