// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/internal/utils"
	"time"
)

type EntityItem struct {
	// Entity ID
	ID string `json:"_id"`
	// Title of the entity
	Title string `json:"_title"`
	// Organization ID the entity belongs to
	Org string `json:"_org"`
	// Array of entity tags
	Tags []string `json:"_tags,omitempty"`
	// Creation timestamp of the entity
	CreatedAt time.Time `json:"_created_at"`
	// Last update timestamp of the entity
	UpdatedAt time.Time `json:"_updated_at"`
	// Resolved template strings corresponding to the templates parameter
	TemplatesOutput map[string]string `json:"templates_output,omitempty"`
	// Entity schema identifier
	Schema               string `json:"_schema"`
	AdditionalProperties any    `additionalProperties:"true" json:"-"`
}

func (e EntityItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntityItem) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EntityItem) GetTitle() string {
	if e == nil {
		return ""
	}
	return e.Title
}

func (e *EntityItem) GetOrg() string {
	if e == nil {
		return ""
	}
	return e.Org
}

func (e *EntityItem) GetTags() []string {
	if e == nil {
		return nil
	}
	return e.Tags
}

func (e *EntityItem) GetCreatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.CreatedAt
}

func (e *EntityItem) GetUpdatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.UpdatedAt
}

func (e *EntityItem) GetTemplatesOutput() map[string]string {
	if e == nil {
		return nil
	}
	return e.TemplatesOutput
}

func (e *EntityItem) GetSchema() string {
	if e == nil {
		return ""
	}
	return e.Schema
}

func (e *EntityItem) GetAdditionalProperties() any {
	if e == nil {
		return nil
	}
	return e.AdditionalProperties
}
