// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/internal/utils"
)

// EntityResponseGroupedWithHitsPagination - Pagination metadata for entities within this group
type EntityResponseGroupedWithHitsPagination struct {
	// Starting offset for entities in this group
	From *float64 `json:"from,omitempty"`
	// Number of entities returned for this group
	Size *float64 `json:"size,omitempty"`
	// Total number of entities available in this group
	Total *float64 `json:"total,omitempty"`
	// Whether there are more entities available in this group beyond the current page
	HasMore *bool `json:"has_more,omitempty"`
}

func (e EntityResponseGroupedWithHitsPagination) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityResponseGroupedWithHitsPagination) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntityResponseGroupedWithHitsPagination) GetFrom() *float64 {
	if e == nil {
		return nil
	}
	return e.From
}

func (e *EntityResponseGroupedWithHitsPagination) GetSize() *float64 {
	if e == nil {
		return nil
	}
	return e.Size
}

func (e *EntityResponseGroupedWithHitsPagination) GetTotal() *float64 {
	if e == nil {
		return nil
	}
	return e.Total
}

func (e *EntityResponseGroupedWithHitsPagination) GetHasMore() *bool {
	if e == nil {
		return nil
	}
	return e.HasMore
}

type Groups struct {
	// Group title
	Group *string `json:"group,omitempty"`
	// Resolved group title from variable
	GroupTitle *string `json:"group_title,omitempty"`
	// Total number of entities in this group
	Count   *float64     `json:"count,omitempty"`
	Results []EntityItem `json:"results,omitempty"`
	// Pagination metadata for entities within this group
	Pagination *EntityResponseGroupedWithHitsPagination `json:"pagination,omitempty"`
}

func (g Groups) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *Groups) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *Groups) GetGroup() *string {
	if g == nil {
		return nil
	}
	return g.Group
}

func (g *Groups) GetGroupTitle() *string {
	if g == nil {
		return nil
	}
	return g.GroupTitle
}

func (g *Groups) GetCount() *float64 {
	if g == nil {
		return nil
	}
	return g.Count
}

func (g *Groups) GetResults() []EntityItem {
	if g == nil {
		return nil
	}
	return g.Results
}

func (g *Groups) GetPagination() *EntityResponseGroupedWithHitsPagination {
	if g == nil {
		return nil
	}
	return g.Pagination
}

// GroupsPagination - Group pagination metadata
type GroupsPagination struct {
	// Whether there are more groups available
	HasMore *bool `json:"has_more,omitempty"`
	// Composite aggregation key for the next page
	AfterKey map[string]string `json:"after_key,omitempty"`
}

func (g GroupsPagination) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GroupsPagination) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GroupsPagination) GetHasMore() *bool {
	if g == nil {
		return nil
	}
	return g.HasMore
}

func (g *GroupsPagination) GetAfterKey() map[string]string {
	if g == nil {
		return nil
	}
	return g.AfterKey
}

// EntityResponseGroupedWithHits - Response for entity search requests, but with groupings
type EntityResponseGroupedWithHits struct {
	Groups []Groups `json:"groups,omitempty"`
	// Group pagination metadata
	GroupsPagination *GroupsPagination `json:"groups_pagination,omitempty"`
	// Number of groups returned in this response
	Hits *float64 `json:"hits,omitempty"`
}

func (e EntityResponseGroupedWithHits) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityResponseGroupedWithHits) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntityResponseGroupedWithHits) GetGroups() []Groups {
	if e == nil {
		return nil
	}
	return e.Groups
}

func (e *EntityResponseGroupedWithHits) GetGroupsPagination() *GroupsPagination {
	if e == nil {
		return nil
	}
	return e.GroupsPagination
}

func (e *EntityResponseGroupedWithHits) GetHits() *float64 {
	if e == nil {
		return nil
	}
	return e.Hits
}
