// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/internal/utils"
)

type ValueType string

const (
	ValueTypeStr           ValueType = "str"
	ValueTypeNumber        ValueType = "number"
	ValueTypeArrayOfStr    ValueType = "arrayOfStr"
	ValueTypeArrayOfNumber ValueType = "arrayOfNumber"
)

// Value - Filter value (string, number, array of strings, or array of numbers). Arrays are used with 'in' and 'notIn' operators.
type Value struct {
	Str           *string   `queryParam:"inline" union:"member"`
	Number        *float64  `queryParam:"inline" union:"member"`
	ArrayOfStr    []string  `queryParam:"inline" union:"member"`
	ArrayOfNumber []float64 `queryParam:"inline" union:"member"`

	Type ValueType
}

func CreateValueStr(str string) Value {
	typ := ValueTypeStr

	return Value{
		Str:  &str,
		Type: typ,
	}
}

func CreateValueNumber(number float64) Value {
	typ := ValueTypeNumber

	return Value{
		Number: &number,
		Type:   typ,
	}
}

func CreateValueArrayOfStr(arrayOfStr []string) Value {
	typ := ValueTypeArrayOfStr

	return Value{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func CreateValueArrayOfNumber(arrayOfNumber []float64) Value {
	typ := ValueTypeArrayOfNumber

	return Value{
		ArrayOfNumber: arrayOfNumber,
		Type:          typ,
	}
}

func (u *Value) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueTypeStr,
			Value: &str,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueTypeNumber,
			Value: &number,
		})
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueTypeArrayOfStr,
			Value: arrayOfStr,
		})
	}

	var arrayOfNumber []float64 = []float64{}
	if err := utils.UnmarshalJSON(data, &arrayOfNumber, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueTypeArrayOfNumber,
			Value: arrayOfNumber,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ValueType)
	switch best.Type {
	case ValueTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case ValueTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case ValueTypeArrayOfStr:
		u.ArrayOfStr = best.Value.([]string)
		return nil
	case ValueTypeArrayOfNumber:
		u.ArrayOfNumber = best.Value.([]float64)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Value", string(data))
}

func (u Value) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	if u.ArrayOfNumber != nil {
		return utils.MarshalJSON(u.ArrayOfNumber, "", true)
	}

	return nil, errors.New("could not marshal union type Value: all fields are null")
}

type FilterCondition struct {
	// Field name to filter on
	Field string `json:"field"`
	// Filter operator
	Operator FilterOperator `json:"operator"`
	// Filter value (string, number, array of strings, or array of numbers). Arrays are used with 'in' and 'notIn' operators.
	Value Value `json:"value"`
}

func (f FilterCondition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FilterCondition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FilterCondition) GetField() string {
	if f == nil {
		return ""
	}
	return f.Field
}

func (f *FilterCondition) GetOperator() FilterOperator {
	if f == nil {
		return FilterOperator("")
	}
	return f.Operator
}

func (f *FilterCondition) GetValue() Value {
	if f == nil {
		return Value{}
	}
	return f.Value
}
