// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// FilterOperator - Filter operator
type FilterOperator string

const (
	FilterOperatorEqual              FilterOperator = "equal"
	FilterOperatorNotEqual           FilterOperator = "not-equal"
	FilterOperatorGreaterThan        FilterOperator = "greater-than"
	FilterOperatorGreaterThanOrEqual FilterOperator = "greater-than-or-equal"
	FilterOperatorLessThan           FilterOperator = "less-than"
	FilterOperatorLessThanOrEqual    FilterOperator = "less-than-or-equal"
	FilterOperatorContains           FilterOperator = "contains"
	FilterOperatorIn                 FilterOperator = "in"
	FilterOperatorNotIn              FilterOperator = "notIn"
)

func (e FilterOperator) ToPointer() *FilterOperator {
	return &e
}
func (e *FilterOperator) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "equal":
		fallthrough
	case "not-equal":
		fallthrough
	case "greater-than":
		fallthrough
	case "greater-than-or-equal":
		fallthrough
	case "less-than":
		fallthrough
	case "less-than-or-equal":
		fallthrough
	case "contains":
		fallthrough
	case "in":
		fallthrough
	case "notIn":
		*e = FilterOperator(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FilterOperator: %v", v)
	}
}
