// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/internal/utils"
)

type FiltersType string

const (
	FiltersTypeStr             FiltersType = "str"
	FiltersTypeFilterCondition FiltersType = "FilterCondition"
)

type Filters struct {
	Str             *string          `queryParam:"inline" union:"member"`
	FilterCondition *FilterCondition `queryParam:"inline" union:"member"`

	Type FiltersType
}

func CreateFiltersStr(str string) Filters {
	typ := FiltersTypeStr

	return Filters{
		Str:  &str,
		Type: typ,
	}
}

func CreateFiltersFilterCondition(filterCondition FilterCondition) Filters {
	typ := FiltersTypeFilterCondition

	return Filters{
		FilterCondition: &filterCondition,
		Type:            typ,
	}
}

func (u *Filters) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FiltersTypeStr,
			Value: &str,
		})
	}

	var filterCondition FilterCondition = FilterCondition{}
	if err := utils.UnmarshalJSON(data, &filterCondition, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FiltersTypeFilterCondition,
			Value: &filterCondition,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Filters", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Filters", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(FiltersType)
	switch best.Type {
	case FiltersTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case FiltersTypeFilterCondition:
		u.FilterCondition = best.Value.(*FilterCondition)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Filters", string(data))
}

func (u Filters) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.FilterCondition != nil {
		return utils.MarshalJSON(u.FilterCondition, "", true)
	}

	return nil, errors.New("could not marshal union type Filters: all fields are null")
}
