// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GroupParams struct {
	// Field to group results by
	By string `json:"by"`
}

func (g *GroupParams) GetBy() string {
	if g == nil {
		return ""
	}
	return g.By
}
