// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SchemaDefinition struct {
	// Schema slug identifier
	Slug       string      `json:"slug"`
	Attributes []Attribute `json:"attributes"`
}

func (s *SchemaDefinition) GetSlug() string {
	if s == nil {
		return ""
	}
	return s.Slug
}

func (s *SchemaDefinition) GetAttributes() []Attribute {
	if s == nil {
		return []Attribute{}
	}
	return s.Attributes
}
