// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SearchParams struct {
	// List of fields to search in
	Fields []string `json:"fields"`
	// Search query string
	Query *string `json:"query,omitempty"`
}

func (s *SearchParams) GetFields() []string {
	if s == nil {
		return []string{}
	}
	return s.Fields
}

func (s *SearchParams) GetQuery() *string {
	if s == nil {
		return nil
	}
	return s.Query
}
