// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/internal/utils"
)

type TargetDatasourceFilter struct {
	// ID of the filter
	ID *string `json:"id,omitempty"`
	// Target ID
	TargetID string `json:"targetId"`
}

func (t TargetDatasourceFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TargetDatasourceFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TargetDatasourceFilter) GetID() *string {
	if t == nil {
		return nil
	}
	return t.ID
}

func (t *TargetDatasourceFilter) GetTargetID() string {
	if t == nil {
		return ""
	}
	return t.TargetID
}
