// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/internal/utils"
)

type VariableValueType string

const (
	VariableValueTypeVariable VariableValueType = "variable"
)

func (e VariableValueType) ToPointer() *VariableValueType {
	return &e
}
func (e *VariableValueType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "variable":
		*e = VariableValueType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VariableValueType: %v", v)
	}
}

type VariableValue struct {
	Type *VariableValueType `json:"type,omitempty"`
	// Variable name
	Variable *string `json:"variable,omitempty"`
	// Preview with value
	PreviewWith *string `json:"previewWith,omitempty"`
}

func (v VariableValue) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VariableValue) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VariableValue) GetType() *VariableValueType {
	if v == nil {
		return nil
	}
	return v.Type
}

func (v *VariableValue) GetVariable() *string {
	if v == nil {
		return nil
	}
	return v.Variable
}

func (v *VariableValue) GetPreviewWith() *string {
	if v == nil {
		return nil
	}
	return v.PreviewWith
}
