// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-datasource/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *DatasourceResourceModel) RefreshFromSharedDatasource(ctx context.Context, resp *shared.Datasource) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CompositeID = types.StringPointerValue(resp.CompositeID)
		r.Fields = make([]types.String, 0, len(resp.Fields))
		for _, v := range resp.Fields {
			r.Fields = append(r.Fields, types.StringValue(v))
		}
		r.Filters = nil
		for _, filtersItem := range resp.Filters {
			var filters []tfTypes.DatasourceFilter
			filters = []tfTypes.DatasourceFilter{}

			for _, filtersItem1 := range filtersItem {
				var filters1 tfTypes.DatasourceFilter

				if filtersItem1.ClassicDatasourceFilter != nil {
					filters1.ClassicDatasourceFilter = &tfTypes.ClassicDatasourceFilter{}
					if filters1.ClassicDatasourceFilter.ComparisonValue == nil {
						filters1.ClassicDatasourceFilter.ComparisonValue = &tfTypes.ComparisonValue{}
					}
					if filtersItem1.ClassicDatasourceFilter.ComparisonValue.BlockValue != nil {
						filters1.ClassicDatasourceFilter.ComparisonValue.BlockValue = &tfTypes.BlockValue{}
						filters1.ClassicDatasourceFilter.ComparisonValue.BlockValue.BlockID = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.BlockValue.BlockID)
						filters1.ClassicDatasourceFilter.ComparisonValue.BlockValue.Path = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.BlockValue.Path)
						filters1.ClassicDatasourceFilter.ComparisonValue.BlockValue.PreviewWith = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.BlockValue.PreviewWith)
						if filtersItem1.ClassicDatasourceFilter.ComparisonValue.BlockValue.Type != nil {
							filters1.ClassicDatasourceFilter.ComparisonValue.BlockValue.Type = types.StringValue(string(*filtersItem1.ClassicDatasourceFilter.ComparisonValue.BlockValue.Type))
						} else {
							filters1.ClassicDatasourceFilter.ComparisonValue.BlockValue.Type = types.StringNull()
						}
					}
					if filtersItem1.ClassicDatasourceFilter.ComparisonValue.ConstantValue != nil {
						filters1.ClassicDatasourceFilter.ComparisonValue.ConstantValue = &tfTypes.ConstantValue{}
						filters1.ClassicDatasourceFilter.ComparisonValue.ConstantValue.PreviewWith = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.ConstantValue.PreviewWith)
						filters1.ClassicDatasourceFilter.ComparisonValue.ConstantValue.Type = types.StringValue(string(filtersItem1.ClassicDatasourceFilter.ComparisonValue.ConstantValue.Type))
						filters1.ClassicDatasourceFilter.ComparisonValue.ConstantValue.Value = types.StringValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.ConstantValue.Value)
					}
					if filtersItem1.ClassicDatasourceFilter.ComparisonValue.ContextValue != nil {
						filters1.ClassicDatasourceFilter.ComparisonValue.ContextValue = &tfTypes.ContextValue{}
						filters1.ClassicDatasourceFilter.ComparisonValue.ContextValue.ContextParameterID = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.ContextValue.ContextParameterID)
						filters1.ClassicDatasourceFilter.ComparisonValue.ContextValue.PreviewWith = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.ContextValue.PreviewWith)
						if filtersItem1.ClassicDatasourceFilter.ComparisonValue.ContextValue.Type != nil {
							filters1.ClassicDatasourceFilter.ComparisonValue.ContextValue.Type = types.StringValue(string(*filtersItem1.ClassicDatasourceFilter.ComparisonValue.ContextValue.Type))
						} else {
							filters1.ClassicDatasourceFilter.ComparisonValue.ContextValue.Type = types.StringNull()
						}
					}
					if filtersItem1.ClassicDatasourceFilter.ComparisonValue.VariableValue != nil {
						filters1.ClassicDatasourceFilter.ComparisonValue.VariableValue = &tfTypes.VariableValue{}
						filters1.ClassicDatasourceFilter.ComparisonValue.VariableValue.PreviewWith = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.VariableValue.PreviewWith)
						if filtersItem1.ClassicDatasourceFilter.ComparisonValue.VariableValue.Type != nil {
							filters1.ClassicDatasourceFilter.ComparisonValue.VariableValue.Type = types.StringValue(string(*filtersItem1.ClassicDatasourceFilter.ComparisonValue.VariableValue.Type))
						} else {
							filters1.ClassicDatasourceFilter.ComparisonValue.VariableValue.Type = types.StringNull()
						}
						filters1.ClassicDatasourceFilter.ComparisonValue.VariableValue.Variable = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.VariableValue.Variable)
					}
					filters1.ClassicDatasourceFilter.Field = types.StringValue(filtersItem1.ClassicDatasourceFilter.Field)
					filters1.ClassicDatasourceFilter.ID = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ID)
					filters1.ClassicDatasourceFilter.Operator = types.StringValue(string(filtersItem1.ClassicDatasourceFilter.Operator))
				}
				if filtersItem1.TargetDatasourceFilter != nil {
					filters1.TargetDatasourceFilter = &tfTypes.TargetDatasourceFilter{}
					filters1.TargetDatasourceFilter.ID = types.StringPointerValue(filtersItem1.TargetDatasourceFilter.ID)
					filters1.TargetDatasourceFilter.TargetID = types.StringValue(filtersItem1.TargetDatasourceFilter.TargetID)
				}

				filters = append(filters, filters1)
			}
			r.Filters = append(r.Filters, filters)
		}
		if resp.Group == nil {
			r.Group = nil
		} else {
			r.Group = &tfTypes.GroupParams{}
			r.Group.By = types.StringValue(resp.Group.By)
		}
		r.ID = types.StringPointerValue(resp.ID)
		r.JourneyID = types.StringPointerValue(resp.JourneyID)
		r.Name = types.StringValue(resp.Name)
		if resp.Search == nil {
			r.Search = nil
		} else {
			r.Search = &tfTypes.SearchParams{}
			r.Search.Fields = make([]types.String, 0, len(resp.Search.Fields))
			for _, v := range resp.Search.Fields {
				r.Search.Fields = append(r.Search.Fields, types.StringValue(v))
			}
			r.Search.Query = types.StringPointerValue(resp.Search.Query)
		}
		r.Source = types.StringValue(resp.Source)
	}

	return diags
}

func (r *DatasourceResourceModel) ToOperationsGetJourneyDatasourceByCompositeIDRequest(ctx context.Context) (*operations.GetJourneyDatasourceByCompositeIDRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var compositeID string
	compositeID = r.CompositeID.ValueString()

	out := operations.GetJourneyDatasourceByCompositeIDRequest{
		CompositeID: compositeID,
	}

	return &out, diags
}

func (r *DatasourceResourceModel) ToSharedDatasourceUpsertRequest(ctx context.Context) (*shared.DatasourceUpsertRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	var id string
	id = r.ID.ValueString()

	var journeyID string
	journeyID = r.JourneyID.ValueString()

	compositeID := new(string)
	if !r.CompositeID.IsUnknown() && !r.CompositeID.IsNull() {
		*compositeID = r.CompositeID.ValueString()
	} else {
		compositeID = nil
	}
	var source string
	source = r.Source.ValueString()

	fields := make([]string, 0, len(r.Fields))
	for fieldsIndex := range r.Fields {
		fields = append(fields, r.Fields[fieldsIndex].ValueString())
	}
	filters := make([][]shared.DatasourceFilter, 0, len(r.Filters))
	for filtersIndex := range r.Filters {
		filtersTmp := make([]shared.DatasourceFilter, 0, len(r.Filters[filtersIndex]))
		for item := range r.Filters[filtersIndex] {
			if r.Filters[filtersIndex][item].ClassicDatasourceFilter != nil {
				id1 := new(string)
				if !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ID.IsUnknown() && !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ID.IsNull() {
					*id1 = r.Filters[filtersIndex][item].ClassicDatasourceFilter.ID.ValueString()
				} else {
					id1 = nil
				}
				var field string
				field = r.Filters[filtersIndex][item].ClassicDatasourceFilter.Field.ValueString()

				operator := shared.FilterOperator(r.Filters[filtersIndex][item].ClassicDatasourceFilter.Operator.ValueString())
				var comparisonValue shared.ComparisonValue
				var constantValue *shared.ConstantValue
				if r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.ConstantValue != nil {
					typeVar := shared.Type(r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.ConstantValue.Type.ValueString())
					var value string
					value = r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.ConstantValue.Value.ValueString()

					previewWith := new(string)
					if !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.ConstantValue.PreviewWith.IsUnknown() && !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.ConstantValue.PreviewWith.IsNull() {
						*previewWith = r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.ConstantValue.PreviewWith.ValueString()
					} else {
						previewWith = nil
					}
					constantValue = &shared.ConstantValue{
						Type:        typeVar,
						Value:       value,
						PreviewWith: previewWith,
					}
				}
				if constantValue != nil {
					comparisonValue = shared.ComparisonValue{
						ConstantValue: constantValue,
					}
				}
				var blockValue *shared.BlockValue
				if r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.BlockValue != nil {
					typeVar1 := new(shared.BlockValueType)
					if !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.BlockValue.Type.IsUnknown() && !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.BlockValue.Type.IsNull() {
						*typeVar1 = shared.BlockValueType(r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.BlockValue.Type.ValueString())
					} else {
						typeVar1 = nil
					}
					blockID := new(string)
					if !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.BlockValue.BlockID.IsUnknown() && !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.BlockValue.BlockID.IsNull() {
						*blockID = r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.BlockValue.BlockID.ValueString()
					} else {
						blockID = nil
					}
					path := new(string)
					if !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.BlockValue.Path.IsUnknown() && !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.BlockValue.Path.IsNull() {
						*path = r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.BlockValue.Path.ValueString()
					} else {
						path = nil
					}
					previewWith1 := new(string)
					if !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.BlockValue.PreviewWith.IsUnknown() && !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.BlockValue.PreviewWith.IsNull() {
						*previewWith1 = r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.BlockValue.PreviewWith.ValueString()
					} else {
						previewWith1 = nil
					}
					blockValue = &shared.BlockValue{
						Type:        typeVar1,
						BlockID:     blockID,
						Path:        path,
						PreviewWith: previewWith1,
					}
				}
				if blockValue != nil {
					comparisonValue = shared.ComparisonValue{
						BlockValue: blockValue,
					}
				}
				var variableValue *shared.VariableValue
				if r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.VariableValue != nil {
					typeVar2 := new(shared.VariableValueType)
					if !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.VariableValue.Type.IsUnknown() && !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.VariableValue.Type.IsNull() {
						*typeVar2 = shared.VariableValueType(r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.VariableValue.Type.ValueString())
					} else {
						typeVar2 = nil
					}
					variable := new(string)
					if !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.VariableValue.Variable.IsUnknown() && !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.VariableValue.Variable.IsNull() {
						*variable = r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.VariableValue.Variable.ValueString()
					} else {
						variable = nil
					}
					previewWith2 := new(string)
					if !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.VariableValue.PreviewWith.IsUnknown() && !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.VariableValue.PreviewWith.IsNull() {
						*previewWith2 = r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.VariableValue.PreviewWith.ValueString()
					} else {
						previewWith2 = nil
					}
					variableValue = &shared.VariableValue{
						Type:        typeVar2,
						Variable:    variable,
						PreviewWith: previewWith2,
					}
				}
				if variableValue != nil {
					comparisonValue = shared.ComparisonValue{
						VariableValue: variableValue,
					}
				}
				var contextValue *shared.ContextValue
				if r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.ContextValue != nil {
					typeVar3 := new(shared.ContextValueType)
					if !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.ContextValue.Type.IsUnknown() && !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.ContextValue.Type.IsNull() {
						*typeVar3 = shared.ContextValueType(r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.ContextValue.Type.ValueString())
					} else {
						typeVar3 = nil
					}
					contextParameterID := new(string)
					if !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.ContextValue.ContextParameterID.IsUnknown() && !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.ContextValue.ContextParameterID.IsNull() {
						*contextParameterID = r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.ContextValue.ContextParameterID.ValueString()
					} else {
						contextParameterID = nil
					}
					previewWith3 := new(string)
					if !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.ContextValue.PreviewWith.IsUnknown() && !r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.ContextValue.PreviewWith.IsNull() {
						*previewWith3 = r.Filters[filtersIndex][item].ClassicDatasourceFilter.ComparisonValue.ContextValue.PreviewWith.ValueString()
					} else {
						previewWith3 = nil
					}
					contextValue = &shared.ContextValue{
						Type:               typeVar3,
						ContextParameterID: contextParameterID,
						PreviewWith:        previewWith3,
					}
				}
				if contextValue != nil {
					comparisonValue = shared.ComparisonValue{
						ContextValue: contextValue,
					}
				}
				classicDatasourceFilter := shared.ClassicDatasourceFilter{
					ID:              id1,
					Field:           field,
					Operator:        operator,
					ComparisonValue: comparisonValue,
				}
				filtersTmp = append(filtersTmp, shared.DatasourceFilter{
					ClassicDatasourceFilter: &classicDatasourceFilter,
				})
			}
			if r.Filters[filtersIndex][item].TargetDatasourceFilter != nil {
				id2 := new(string)
				if !r.Filters[filtersIndex][item].TargetDatasourceFilter.ID.IsUnknown() && !r.Filters[filtersIndex][item].TargetDatasourceFilter.ID.IsNull() {
					*id2 = r.Filters[filtersIndex][item].TargetDatasourceFilter.ID.ValueString()
				} else {
					id2 = nil
				}
				var targetID string
				targetID = r.Filters[filtersIndex][item].TargetDatasourceFilter.TargetID.ValueString()

				targetDatasourceFilter := shared.TargetDatasourceFilter{
					ID:       id2,
					TargetID: targetID,
				}
				filtersTmp = append(filtersTmp, shared.DatasourceFilter{
					TargetDatasourceFilter: &targetDatasourceFilter,
				})
			}
		}
		filters = append(filters, filtersTmp)
	}
	var search *shared.SearchParams
	if r.Search != nil {
		fields1 := make([]string, 0, len(r.Search.Fields))
		for fieldsIndex1 := range r.Search.Fields {
			fields1 = append(fields1, r.Search.Fields[fieldsIndex1].ValueString())
		}
		query := new(string)
		if !r.Search.Query.IsUnknown() && !r.Search.Query.IsNull() {
			*query = r.Search.Query.ValueString()
		} else {
			query = nil
		}
		search = &shared.SearchParams{
			Fields: fields1,
			Query:  query,
		}
	}
	var group *shared.GroupParams
	if r.Group != nil {
		var by string
		by = r.Group.By.ValueString()

		group = &shared.GroupParams{
			By: by,
		}
	}
	out := shared.DatasourceUpsertRequest{
		Name:        name,
		ID:          id,
		JourneyID:   journeyID,
		CompositeID: compositeID,
		Source:      source,
		Fields:      fields,
		Filters:     filters,
		Search:      search,
		Group:       group,
	}

	return &out, diags
}
