// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-datasource/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk"
	speakeasy_listvalidators "github.com/epilot-dev/terraform-provider-epilot-datasource/internal/validators/listvalidators"
	speakeasy_stringvalidators "github.com/epilot-dev/terraform-provider-epilot-datasource/internal/validators/stringvalidators"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &DatasourceResource{}
var _ resource.ResourceWithImportState = &DatasourceResource{}

func NewDatasourceResource() resource.Resource {
	return &DatasourceResource{}
}

// DatasourceResource defines the resource implementation.
type DatasourceResource struct {
	// Provider configured SDK client.
	client *sdk.SDK
}

// DatasourceResourceModel describes the resource data model.
type DatasourceResourceModel struct {
	CompositeID types.String                 `tfsdk:"composite_id"`
	Fields      []types.String               `tfsdk:"fields"`
	Filters     [][]tfTypes.DatasourceFilter `tfsdk:"filters"`
	Group       *tfTypes.GroupParams         `tfsdk:"group"`
	ID          types.String                 `tfsdk:"id"`
	JourneyID   types.String                 `tfsdk:"journey_id"`
	Name        types.String                 `tfsdk:"name"`
	Search      *tfTypes.SearchParams        `tfsdk:"search"`
	Source      types.String                 `tfsdk:"source"`
}

func (r *DatasourceResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_datasource"
}

func (r *DatasourceResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Datasource Resource",
		Attributes: map[string]schema.Attribute{
			"composite_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: `Composite identifier in the form ` + "`" + `journeyId:datasourceId` + "`" + `. Returned by GET responses and accepted by endpoints that look up a datasource by composite id.`,
			},
			"fields": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
				Description: `List of entity fields to include in search results`,
			},
			"filters": schema.ListAttribute{
				Computed: true,
				Optional: true,
				ElementType: types.ListType{
					ElemType: types.ObjectType{
						AttrTypes: map[string]attr.Type{
							`classic_datasource_filter`: types.ObjectType{
								AttrTypes: map[string]attr.Type{
									`comparison_value`: types.ObjectType{
										AttrTypes: map[string]attr.Type{
											`block_value`: types.ObjectType{
												AttrTypes: map[string]attr.Type{
													`block_id`:     types.StringType,
													`path`:         types.StringType,
													`preview_with`: types.StringType,
													`type`:         types.StringType,
												},
											},
											`constant_value`: types.ObjectType{
												AttrTypes: map[string]attr.Type{
													`preview_with`: types.StringType,
													`type`:         types.StringType,
													`value`:        types.StringType,
												},
											},
											`context_value`: types.ObjectType{
												AttrTypes: map[string]attr.Type{
													`context_parameter_id`: types.StringType,
													`preview_with`:         types.StringType,
													`type`:                 types.StringType,
												},
											},
											`variable_value`: types.ObjectType{
												AttrTypes: map[string]attr.Type{
													`preview_with`: types.StringType,
													`type`:         types.StringType,
													`variable`:     types.StringType,
												},
											},
										},
									},
									`field`:    types.StringType,
									`id`:       types.StringType,
									`operator`: types.StringType,
								},
							},
							`target_datasource_filter`: types.ObjectType{
								AttrTypes: map[string]attr.Type{
									`id`:        types.StringType,
									`target_id`: types.StringType,
								},
							},
						},
					},
				},
			},
			"group": schema.SingleNestedAttribute{
				Computed: true,
				Optional: true,
				Attributes: map[string]schema.Attribute{
					"by": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: `Field to group results by. Not Null`,
						Validators: []validator.String{
							speakeasy_stringvalidators.NotNull(),
						},
					},
				},
			},
			"id": schema.StringAttribute{
				Required:    true,
				Description: `ID of the datasource`,
			},
			"journey_id": schema.StringAttribute{
				Required:    true,
				Description: `Journey ID`,
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: `Name of the datasource`,
			},
			"search": schema.SingleNestedAttribute{
				Computed: true,
				Optional: true,
				Attributes: map[string]schema.Attribute{
					"fields": schema.ListAttribute{
						Computed:    true,
						Optional:    true,
						ElementType: types.StringType,
						Description: `List of fields to search in. Not Null`,
						Validators: []validator.List{
							speakeasy_listvalidators.NotNull(),
						},
					},
					"query": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: `Search query string`,
					},
				},
			},
			"source": schema.StringAttribute{
				Required:    true,
				Description: `Source identifier for the search`,
			},
		},
	}
}

func (r *DatasourceResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *DatasourceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *DatasourceResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(plan.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToSharedDatasourceUpsertRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.ThreeHundredAndSixtyMinusNativeJourneys.UpsertJourneyDatasource(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.Datasource != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedDatasource(ctx, res.Datasource)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *DatasourceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *DatasourceResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetJourneyDatasourceByCompositeIDRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.ThreeHundredAndSixtyMinusNativeJourneys.GetJourneyDatasourceByCompositeID(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.Datasource != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedDatasource(ctx, res.Datasource)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *DatasourceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *DatasourceResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToSharedDatasourceUpsertRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.ThreeHundredAndSixtyMinusNativeJourneys.UpsertJourneyDatasource(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.Datasource != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedDatasource(ctx, res.Datasource)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *DatasourceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *DatasourceResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Not Implemented; entity does not have a configured DELETE operation
}

func (r *DatasourceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("composite_id"), req.ID)...)
}
