// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-datasource/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &DatasourceDataSource{}
var _ datasource.DataSourceWithConfigure = &DatasourceDataSource{}

func NewDatasourceDataSource() datasource.DataSource {
	return &DatasourceDataSource{}
}

// DatasourceDataSource is the data source implementation.
type DatasourceDataSource struct {
	// Provider configured SDK client.
	client *sdk.SDK
}

// DatasourceDataSourceModel describes the data model.
type DatasourceDataSourceModel struct {
	CompositeID types.String                 `tfsdk:"composite_id"`
	Fields      []types.String               `tfsdk:"fields"`
	Filters     [][]tfTypes.DatasourceFilter `tfsdk:"filters"`
	Group       *tfTypes.GroupParams         `tfsdk:"group"`
	ID          types.String                 `tfsdk:"id"`
	JourneyID   types.String                 `tfsdk:"journey_id"`
	Name        types.String                 `tfsdk:"name"`
	Search      *tfTypes.SearchParams        `tfsdk:"search"`
	Source      types.String                 `tfsdk:"source"`
}

// Metadata returns the data source type name.
func (r *DatasourceDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_datasource"
}

// Schema defines the schema for the data source.
func (r *DatasourceDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Datasource DataSource",

		Attributes: map[string]schema.Attribute{
			"composite_id": schema.StringAttribute{
				Required:    true,
				Description: `Composite identifier in the form ` + "`" + `journeyId:datasourceId` + "`" + `. Returned by GET responses and accepted by endpoints that look up a datasource by composite id.`,
			},
			"fields": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: `List of entity fields to include in search results`,
			},
			"filters": schema.ListAttribute{
				Computed: true,
				ElementType: types.ListType{
					ElemType: types.ObjectType{
						AttrTypes: map[string]attr.Type{
							`classic_datasource_filter`: types.ObjectType{
								AttrTypes: map[string]attr.Type{
									`comparison_value`: types.ObjectType{
										AttrTypes: map[string]attr.Type{
											`block_value`: types.ObjectType{
												AttrTypes: map[string]attr.Type{
													`block_id`:     types.StringType,
													`path`:         types.StringType,
													`preview_with`: types.StringType,
													`type`:         types.StringType,
												},
											},
											`constant_value`: types.ObjectType{
												AttrTypes: map[string]attr.Type{
													`preview_with`: types.StringType,
													`type`:         types.StringType,
													`value`:        types.StringType,
												},
											},
											`context_value`: types.ObjectType{
												AttrTypes: map[string]attr.Type{
													`context_parameter_id`: types.StringType,
													`preview_with`:         types.StringType,
													`type`:                 types.StringType,
												},
											},
											`variable_value`: types.ObjectType{
												AttrTypes: map[string]attr.Type{
													`preview_with`: types.StringType,
													`type`:         types.StringType,
													`variable`:     types.StringType,
												},
											},
										},
									},
									`field`:    types.StringType,
									`id`:       types.StringType,
									`operator`: types.StringType,
								},
							},
							`target_datasource_filter`: types.ObjectType{
								AttrTypes: map[string]attr.Type{
									`id`:        types.StringType,
									`target_id`: types.StringType,
								},
							},
						},
					},
				},
			},
			"group": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"by": schema.StringAttribute{
						Computed:    true,
						Description: `Field to group results by`,
					},
				},
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Description: `ID of the datasource`,
			},
			"journey_id": schema.StringAttribute{
				Computed:    true,
				Description: `Journey ID`,
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: `Name of the datasource`,
			},
			"search": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"fields": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
						Description: `List of fields to search in`,
					},
					"query": schema.StringAttribute{
						Computed:    true,
						Description: `Search query string`,
					},
				},
			},
			"source": schema.StringAttribute{
				Computed:    true,
				Description: `Source identifier for the search`,
			},
		},
	}
}

func (r *DatasourceDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *DatasourceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *DatasourceDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetJourneyDatasourceByCompositeIDRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.ThreeHundredAndSixtyMinusNativeJourneys.GetJourneyDatasourceByCompositeID(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.Datasource != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedDatasource(ctx, res.Datasource)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
