// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-datasource/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *DatasourceDataSourceModel) RefreshFromSharedDatasource(ctx context.Context, resp *shared.Datasource) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CompositeID = types.StringPointerValue(resp.CompositeID)
		r.Fields = make([]types.String, 0, len(resp.Fields))
		for _, v := range resp.Fields {
			r.Fields = append(r.Fields, types.StringValue(v))
		}
		r.Filters = nil
		for _, filtersItem := range resp.Filters {
			var filters []tfTypes.DatasourceFilter
			filters = []tfTypes.DatasourceFilter{}

			for _, filtersItem1 := range filtersItem {
				var filters1 tfTypes.DatasourceFilter

				if filtersItem1.ClassicDatasourceFilter != nil {
					filters1.ClassicDatasourceFilter = &tfTypes.ClassicDatasourceFilter{}
					if filters1.ClassicDatasourceFilter.ComparisonValue == nil {
						filters1.ClassicDatasourceFilter.ComparisonValue = &tfTypes.ComparisonValue{}
					}
					if filtersItem1.ClassicDatasourceFilter.ComparisonValue.BlockValue != nil {
						filters1.ClassicDatasourceFilter.ComparisonValue.BlockValue = &tfTypes.BlockValue{}
						filters1.ClassicDatasourceFilter.ComparisonValue.BlockValue.BlockID = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.BlockValue.BlockID)
						filters1.ClassicDatasourceFilter.ComparisonValue.BlockValue.Path = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.BlockValue.Path)
						filters1.ClassicDatasourceFilter.ComparisonValue.BlockValue.PreviewWith = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.BlockValue.PreviewWith)
						if filtersItem1.ClassicDatasourceFilter.ComparisonValue.BlockValue.Type != nil {
							filters1.ClassicDatasourceFilter.ComparisonValue.BlockValue.Type = types.StringValue(string(*filtersItem1.ClassicDatasourceFilter.ComparisonValue.BlockValue.Type))
						} else {
							filters1.ClassicDatasourceFilter.ComparisonValue.BlockValue.Type = types.StringNull()
						}
					}
					if filtersItem1.ClassicDatasourceFilter.ComparisonValue.ConstantValue != nil {
						filters1.ClassicDatasourceFilter.ComparisonValue.ConstantValue = &tfTypes.ConstantValue{}
						filters1.ClassicDatasourceFilter.ComparisonValue.ConstantValue.PreviewWith = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.ConstantValue.PreviewWith)
						filters1.ClassicDatasourceFilter.ComparisonValue.ConstantValue.Type = types.StringValue(string(filtersItem1.ClassicDatasourceFilter.ComparisonValue.ConstantValue.Type))
						filters1.ClassicDatasourceFilter.ComparisonValue.ConstantValue.Value = types.StringValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.ConstantValue.Value)
					}
					if filtersItem1.ClassicDatasourceFilter.ComparisonValue.ContextValue != nil {
						filters1.ClassicDatasourceFilter.ComparisonValue.ContextValue = &tfTypes.ContextValue{}
						filters1.ClassicDatasourceFilter.ComparisonValue.ContextValue.ContextParameterID = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.ContextValue.ContextParameterID)
						filters1.ClassicDatasourceFilter.ComparisonValue.ContextValue.PreviewWith = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.ContextValue.PreviewWith)
						if filtersItem1.ClassicDatasourceFilter.ComparisonValue.ContextValue.Type != nil {
							filters1.ClassicDatasourceFilter.ComparisonValue.ContextValue.Type = types.StringValue(string(*filtersItem1.ClassicDatasourceFilter.ComparisonValue.ContextValue.Type))
						} else {
							filters1.ClassicDatasourceFilter.ComparisonValue.ContextValue.Type = types.StringNull()
						}
					}
					if filtersItem1.ClassicDatasourceFilter.ComparisonValue.VariableValue != nil {
						filters1.ClassicDatasourceFilter.ComparisonValue.VariableValue = &tfTypes.VariableValue{}
						filters1.ClassicDatasourceFilter.ComparisonValue.VariableValue.PreviewWith = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.VariableValue.PreviewWith)
						if filtersItem1.ClassicDatasourceFilter.ComparisonValue.VariableValue.Type != nil {
							filters1.ClassicDatasourceFilter.ComparisonValue.VariableValue.Type = types.StringValue(string(*filtersItem1.ClassicDatasourceFilter.ComparisonValue.VariableValue.Type))
						} else {
							filters1.ClassicDatasourceFilter.ComparisonValue.VariableValue.Type = types.StringNull()
						}
						filters1.ClassicDatasourceFilter.ComparisonValue.VariableValue.Variable = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ComparisonValue.VariableValue.Variable)
					}
					filters1.ClassicDatasourceFilter.Field = types.StringValue(filtersItem1.ClassicDatasourceFilter.Field)
					filters1.ClassicDatasourceFilter.ID = types.StringPointerValue(filtersItem1.ClassicDatasourceFilter.ID)
					filters1.ClassicDatasourceFilter.Operator = types.StringValue(string(filtersItem1.ClassicDatasourceFilter.Operator))
				}
				if filtersItem1.TargetDatasourceFilter != nil {
					filters1.TargetDatasourceFilter = &tfTypes.TargetDatasourceFilter{}
					filters1.TargetDatasourceFilter.ID = types.StringPointerValue(filtersItem1.TargetDatasourceFilter.ID)
					filters1.TargetDatasourceFilter.TargetID = types.StringValue(filtersItem1.TargetDatasourceFilter.TargetID)
				}

				filters = append(filters, filters1)
			}
			r.Filters = append(r.Filters, filters)
		}
		if resp.Group == nil {
			r.Group = nil
		} else {
			r.Group = &tfTypes.GroupParams{}
			r.Group.By = types.StringValue(resp.Group.By)
		}
		r.ID = types.StringPointerValue(resp.ID)
		r.JourneyID = types.StringPointerValue(resp.JourneyID)
		r.Name = types.StringValue(resp.Name)
		if resp.Search == nil {
			r.Search = nil
		} else {
			r.Search = &tfTypes.SearchParams{}
			r.Search.Fields = make([]types.String, 0, len(resp.Search.Fields))
			for _, v := range resp.Search.Fields {
				r.Search.Fields = append(r.Search.Fields, types.StringValue(v))
			}
			r.Search.Query = types.StringPointerValue(resp.Search.Query)
		}
		r.Source = types.StringValue(resp.Source)
	}

	return diags
}

func (r *DatasourceDataSourceModel) ToOperationsGetJourneyDatasourceByCompositeIDRequest(ctx context.Context) (*operations.GetJourneyDatasourceByCompositeIDRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var compositeID string
	compositeID = r.CompositeID.ValueString()

	out := operations.GetJourneyDatasourceByCompositeIDRequest{
		CompositeID: compositeID,
	}

	return &out, diags
}
