// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk"
	"github.com/epilot-dev/terraform-provider-epilot-datasource/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/action"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/ephemeral"
	"github.com/hashicorp/terraform-plugin-framework/function"
	"github.com/hashicorp/terraform-plugin-framework/list"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"net/http"
)

var _ provider.Provider = (*EpilotDatasourceProvider)(nil)
var _ provider.ProviderWithActions = (*EpilotDatasourceProvider)(nil)
var _ provider.ProviderWithEphemeralResources = (*EpilotDatasourceProvider)(nil)
var _ provider.ProviderWithFunctions = (*EpilotDatasourceProvider)(nil)

type EpilotDatasourceProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// EpilotDatasourceProviderModel describes the provider data model.
type EpilotDatasourceProviderModel struct {
	EpilotAuth types.String `tfsdk:"epilot_auth"`
	PortalAuth types.String `tfsdk:"portal_auth"`
	ServerURL  types.String `tfsdk:"server_url"`
}

func (p *EpilotDatasourceProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "epilot-datasource"
	resp.Version = p.version
}

func (p *EpilotDatasourceProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"epilot_auth": schema.StringAttribute{
				MarkdownDescription: `Epilot Authorization Bearer Token - public access token / user token.`,
				Optional:            true,
				Sensitive:           true,
			},
			"portal_auth": schema.StringAttribute{
				MarkdownDescription: `Authorization header with customer portal OAuth2 bearer token.`,
				Optional:            true,
				Sensitive:           true,
			},
			"server_url": schema.StringAttribute{
				Description: `Server URL (defaults to https://epilot360-native-journeys.sls.epilot.io)`,
				Optional:    true,
			},
		},
		MarkdownDescription: `360-native-journeys API: API to configure 360-native-journeys`,
	}
}

func (p *EpilotDatasourceProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data EpilotDatasourceProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	serverUrl := data.ServerURL.ValueString()

	if serverUrl == "" {
		serverUrl = "https://epilot360-native-journeys.sls.epilot.io"
	}

	security := shared.Security{}

	if !data.EpilotAuth.IsUnknown() {
		security.EpilotAuth = data.EpilotAuth.ValueStringPointer()
	}

	if !data.PortalAuth.IsUnknown() {
		security.PortalAuth = data.PortalAuth.ValueStringPointer()
	}

	providerHTTPTransportOpts := ProviderHTTPTransportOpts{
		SetHeaders: make(map[string]string),
		Transport:  http.DefaultTransport,
	}

	httpClient := http.DefaultClient
	httpClient.Transport = NewProviderHTTPTransport(providerHTTPTransportOpts)

	opts := []sdk.SDKOption{
		sdk.WithServerURL(serverUrl),
		sdk.WithSecurity(security),
		sdk.WithClient(httpClient),
	}

	client := sdk.New(opts...)
	resp.ActionData = client
	resp.DataSourceData = client
	resp.EphemeralResourceData = client
	resp.ListResourceData = client
	resp.ResourceData = client
}

func (p *EpilotDatasourceProvider) Functions(_ context.Context) []func() function.Function {
	return []func() function.Function{}
}

func (p *EpilotDatasourceProvider) Actions(_ context.Context) []func() action.Action {
	return []func() action.Action{}
}

func (p *EpilotDatasourceProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewDatasourceResource,
	}
}

func (p *EpilotDatasourceProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{}
}

func (p *EpilotDatasourceProvider) EphemeralResources(ctx context.Context) []func() ephemeral.EphemeralResource {
	return []func() ephemeral.EphemeralResource{}
}

func (p *EpilotDatasourceProvider) ListResources(ctx context.Context) []func() list.ListResource {
	return []func() list.ListResource{}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &EpilotDatasourceProvider{
			version: version,
		}
	}
}
