// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type BlockValue struct {
	BlockID     types.String `tfsdk:"block_id"`
	Path        types.String `tfsdk:"path"`
	PreviewWith types.String `tfsdk:"preview_with"`
	Type        types.String `tfsdk:"type"`
}
