// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ClassicDatasourceFilter struct {
	ComparisonValue *ComparisonValue `tfsdk:"comparison_value"`
	Field           types.String     `tfsdk:"field"`
	ID              types.String     `tfsdk:"id"`
	Operator        types.String     `tfsdk:"operator"`
}
