// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type ComparisonValue struct {
	BlockValue    *BlockValue    `queryParam:"inline" tfsdk:"block_value"`
	ConstantValue *ConstantValue `queryParam:"inline" tfsdk:"constant_value"`
	ContextValue  *ContextValue  `queryParam:"inline" tfsdk:"context_value"`
	VariableValue *VariableValue `queryParam:"inline" tfsdk:"variable_value"`
}
