// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ContextValue struct {
	ContextParameterID types.String `tfsdk:"context_parameter_id"`
	PreviewWith        types.String `tfsdk:"preview_with"`
	Type               types.String `tfsdk:"type"`
}
