// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type DatasourceFilter struct {
	ClassicDatasourceFilter *ClassicDatasourceFilter `queryParam:"inline" tfsdk:"classic_datasource_filter"`
	TargetDatasourceFilter  *TargetDatasourceFilter  `queryParam:"inline" tfsdk:"target_datasource_filter"`
}
