// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type SearchParams struct {
	Fields []types.String `tfsdk:"fields"`
	Query  types.String   `tfsdk:"query"`
}
